security:
    # https://symfony.com/doc/current/security.html#c-hashing-passwords
    password_hashers:
        App\Entity\User: "auto"

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        users:
            entity:
                class: App\Entity\User
                property: email
            # mongodb:
            #    class: App\Document\User
            #    property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js|assets|bundles)/
            security: false
        app:
            pattern: ^/(login|logout|register|verify-email|profile)
            provider: users
            form_login:
                check_path: app_login
                login_path: app_login
            logout: ~
        api:
            stateless: true
            provider: users
            json_login:
                check_path: api_auth
                username_path: email
                password_path: password
                success_handler: lexik_jwt_authentication.handler.authentication_success
                failure_handler: lexik_jwt_authentication.handler.authentication_failure
            jwt: ~
    access_control:
        - { path: ^/$, roles: PUBLIC_ACCESS } # Allows accessing the Swagger UI
        - { path: ^/docs, roles: PUBLIC_ACCESS } # Allows accessing the Swagger UI docs
        - { path: ^/contexts, roles: PUBLIC_ACCESS } # Allows accessing the Swagger UI contexts
        - { path: ^/auth, roles: PUBLIC_ACCESS }
        - { path: /login, roles: PUBLIC_ACCESS }
        - { path: /register, roles: PUBLIC_ACCESS }
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
