<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260404041008 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'issue_keyword relation table';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE issue_keyword (issue_id INT NOT NULL, keyword_id INT NOT NULL, PRIMARY KEY (issue_id, keyword_id))');
        $this->addSql('CREATE INDEX IDX_FF6B34DA5E7AA58C ON issue_keyword (issue_id)');
        $this->addSql('CREATE INDEX IDX_FF6B34DA115D4552 ON issue_keyword (keyword_id)');
        $this->addSql('CREATE TABLE keyword (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_5A93713B5E237E06 ON keyword (name)');
        $this->addSql('ALTER TABLE issue_keyword ADD CONSTRAINT FK_FF6B34DA5E7AA58C FOREIGN KEY (issue_id) REFERENCES issue (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE issue_keyword ADD CONSTRAINT FK_FF6B34DA115D4552 FOREIGN KEY (keyword_id) REFERENCES keyword (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE issue_keyword DROP CONSTRAINT FK_FF6B34DA5E7AA58C');
        $this->addSql('ALTER TABLE issue_keyword DROP CONSTRAINT FK_FF6B34DA115D4552');
        $this->addSql('DROP TABLE issue_keyword');
        $this->addSql('DROP TABLE keyword');
    }
}
