--
-- PostgreSQL database dump
--

\restrict PcGgHJWixphncbDMmaQ70sIe2gZSG08hZK30ccrJLDlr4uXnnpjjGxdftcXeCuL

-- Dumped from database version 17.9 (Debian 17.9-1.pgdg13+1)
-- Dumped by pg_dump version 17.9 (Debian 17.9-1.pgdg13+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: doctrine_migration_versions; Type: TABLE; Schema: public; Owner: db
--

CREATE TABLE public.doctrine_migration_versions (
    version character varying(191) NOT NULL,
    executed_at timestamp(0) without time zone DEFAULT NULL::timestamp without time zone,
    execution_time integer
);


ALTER TABLE public.doctrine_migration_versions OWNER TO db;

--
-- Name: todo; Type: TABLE; Schema: public; Owner: db
--

CREATE TABLE public.todo (
    id integer NOT NULL,
    title character varying(128) NOT NULL,
    description character varying(255) DEFAULT NULL::character varying,
    is_done boolean NOT NULL,
    created_at timestamp(0) without time zone NOT NULL,
    updated_at timestamp(0) without time zone NOT NULL
);


ALTER TABLE public.todo OWNER TO db;

--
-- Name: todo_id_seq; Type: SEQUENCE; Schema: public; Owner: db
--

ALTER TABLE public.todo ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.todo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: doctrine_migration_versions; Type: TABLE DATA; Schema: public; Owner: db
--

COPY public.doctrine_migration_versions (version, executed_at, execution_time) FROM stdin;
DoctrineMigrations\\Version20260329093421	2026-03-29 11:34:24	2
\.


--
-- Data for Name: todo; Type: TABLE DATA; Schema: public; Owner: db
--

COPY public.todo (id, title, description, is_done, created_at, updated_at) FROM stdin;
1	Cleanup	Remove unused code	f	2026-03-29 11:34:53	2026-03-29 11:34:53
2	Doctrine filter	Add Doctrine filters to entity	f	2026-03-29 11:57:49	2026-03-29 11:57:49
3	Using DTOs	Using DTOs for entity	f	2026-03-29 11:58:11	2026-03-29 11:58:11
4	Validation	Validate resources and entities	f	2026-03-29 11:58:53	2026-03-29 11:58:53
5	Security	Adding access control	f	2026-03-29 11:59:11	2026-03-29 11:59:11
6	Test Suite	Add tests for entity	f	2026-03-29 12:00:40	2026-03-29 12:00:40
7	Data Fixtures	Generate Data Fixtures	f	2026-03-29 12:01:13	2026-03-29 12:01:13
8	Timestampable	Debug TimestampableEntity behaviour	t	2026-03-29 12:44:09	2026-03-29 12:47:14
9	Plesk Deployment	Deploy Docker-Compose setup to Plesk server	f	2026-03-29 12:53:28	2026-03-29 12:53:28
10	Exception Handling	Create Domain Exception	f	2026-03-29 12:53:56	2026-03-29 12:53:56
12	API Docs	Complete API Docs	f	2026-03-29 13:04:07	2026-03-29 13:04:07
13	Pagination	Extend Pagination configuration	f	2026-03-29 13:41:05	2026-03-29 13:41:05
\.


--
-- Name: todo_id_seq; Type: SEQUENCE SET; Schema: public; Owner: db
--

SELECT pg_catalog.setval('public.todo_id_seq', 13, true);


--
-- Name: doctrine_migration_versions doctrine_migration_versions_pkey; Type: CONSTRAINT; Schema: public; Owner: db
--

ALTER TABLE ONLY public.doctrine_migration_versions
    ADD CONSTRAINT doctrine_migration_versions_pkey PRIMARY KEY (version);


--
-- Name: todo todo_pkey; Type: CONSTRAINT; Schema: public; Owner: db
--

ALTER TABLE ONLY public.todo
    ADD CONSTRAINT todo_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

\unrestrict PcGgHJWixphncbDMmaQ70sIe2gZSG08hZK30ccrJLDlr4uXnnpjjGxdftcXeCuL

